using System.Numerics;

Console.WriteLine("Recipients' Full Name");
string recp = Console.ReadLine();
Console.WriteLine("Your Full Name");
string name = Console.ReadLine();
Console.WriteLine("Letter Subject");
string subj = Console.ReadLine();
Console.WriteLine("Specific Project/Task");
string task = Console.ReadLine();
Console.WriteLine("Followup Date");
string follow = Console.ReadLine();
Console.WriteLine("Generating your letter...");
Console.WriteLine();
Console.WriteLine(DateTime.Now.ToShortDateString());
Console.WriteLine();
Console.WriteLine("To: " + recp);
Console.WriteLine();
Console.WriteLine($"Dear {recp},");
Console.WriteLine();
Console.WriteLine($"Subject: {subj}");
Console.WriteLine($"I am writing to you today regarding {task} that we discussed.");
Console.WriteLine("I wanted to provide a quick update on its progress.");
Console.WriteLine();
Console.WriteLine($"We anticipate completing {task} by {follow}");
Console.WriteLine("Please let me know if you have any questions or require further information.");
Console.WriteLine();
Console.WriteLine("Sincerely,");
Console.WriteLine(name);
Console.WriteLine();

